/** Database adapter and forward-only schema migrations shared by API and workers.
 * PostgreSQL is the sole runtime database locally, in tests and on AWS.
 * Migrations transfer the legacy owner and data without resetting passwords or strategies.
 */
import { resolve } from "node:path";
import { readLocalPostgresConfiguration } from "./local-database.js";
import { fileURLToPath, pathToFileURL } from "node:url";
import pg from "pg";
import type { Settings } from "./types.js";

type Parameter = string | number | boolean | null;
export type Query = <T = Record<string, unknown>>(
  sql: string,
  params?: Parameter[],
) => Promise<T[]>;
export interface Store {
  transaction<T>(fn: (query: Query) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

export const root = fileURLToPath(
  new URL(import.meta.url.endsWith(".ts") ? "../" : "../../", import.meta.url),
);
export const now = () => new Date().toISOString();
export const isEntryPoint = (url: string) =>
  Boolean(
    process.argv[1] && url === pathToFileURL(resolve(process.argv[1])).href,
  );

/** Open one PostgreSQL pool. Local configuration is generated by make run; production
 * requires an explicit DATABASE_URL. No alternate database engine or SQL dialect exists here.
 */
export function openDatabaseStore(
  url = process.env.DATABASE_URL ||
    (process.env.APP_ENV !== "production" &&
    process.env.NODE_ENV !== "production"
      ? readLocalPostgresConfiguration()?.applicationUrl
      : undefined),
): Store {
  if (!url || !/^postgres(?:ql)?:\/\//.test(url)) {
    throw new Error(
      "A PostgreSQL DATABASE_URL is required. Run make run to initialize local PostgreSQL.",
    );
  }
  const pool = new pg.Pool({
    connectionString: url,
    max: 5,
    connectionTimeoutMillis: 5000,
    idleTimeoutMillis: 30000,
    // Dispatch can hold the account gate for a 10s snapshot plus a 3s order call.
    // A kill waiting behind that bounded work must not time out before it finishes.
    statement_timeout: 20000,
    query_timeout: 25000,
    idle_in_transaction_session_timeout: 20000,
  });
  pool.on("error", () =>
    console.error("Database idle connection failed; pool will replace it."),
  );
  const store: Store = {
    /** Commit the callback atomically; rollback failures discard the PostgreSQL connection.
     * Independent requests get independent connections, bounded by the configured pool size.
     */
    async transaction(fn) {
      let client: pg.PoolClient | null = null;
      let broken = true;
      try {
        client = await pool.connect();
        const query: Query = async <T>(
          sql: string,
          params: Parameter[] = [],
        ): Promise<T[]> => {
          return (await client!.query(sql, params)).rows as T[];
        };
        await query("BEGIN");
        broken = false;
        try {
          const value = await fn(query);
          await query("COMMIT");
          return value;
        } catch (error) {
          try {
            await query("ROLLBACK");
          } catch {
            broken = true;
          }
          throw error;
        }
      } finally {
        client?.release(broken);
      }
    },
    /** Drain outstanding PostgreSQL clients during tests or graceful shutdown. */
    async close() {
      await pool.end();
    },
  };
  return store;
}

/** Apply each numbered schema change once, under a migration lock on PostgreSQL.
 * The runtime role gets DML privileges only; migration credentials are never given to the API.
 */
export async function runDatabaseMigrations(
  store: Store,
  options: { runtimePassword?: string; backupPassword?: string } = {
    runtimePassword: process.env.APP_DATABASE_PASSWORD,
    backupPassword: process.env.BACKUP_DATABASE_PASSWORD,
  },
) {
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(684201)");
    await query(
      "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY)",
    );
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=1"))
        .length
    ) {
      for (const sql of [
        "CREATE TABLE IF NOT EXISTS owners (id INTEGER PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, password_hash TEXT NOT NULL, failed_logins INTEGER NOT NULL, locked_until DOUBLE PRECISION NOT NULL)",
        "CREATE TABLE IF NOT EXISTS sessions (token_hash VARCHAR(64) PRIMARY KEY, csrf VARCHAR(100) NOT NULL, expires DOUBLE PRECISION NOT NULL)",
        "CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY, halted BOOLEAN NOT NULL)",
        "CREATE TABLE IF NOT EXISTS strategies (id VARCHAR(36) PRIMARY KEY, name VARCHAR(60) NOT NULL, symbol VARCHAR(20) NOT NULL, fast INTEGER NOT NULL, slow INTEGER NOT NULL, capital INTEGER NOT NULL, status VARCHAR(20) NOT NULL, pnl DOUBLE PRECISION NOT NULL, created_at VARCHAR(40) NOT NULL)",
        "CREATE TABLE IF NOT EXISTS jobs (id VARCHAR(36) PRIMARY KEY, strategy_id VARCHAR(36) NOT NULL, status VARCHAR(20) NOT NULL, result TEXT NOT NULL, created_at VARCHAR(40) NOT NULL, updated_at VARCHAR(40) NOT NULL)",
        "CREATE TABLE IF NOT EXISTS events (id SERIAL PRIMARY KEY, message TEXT NOT NULL, created_at VARCHAR(40) NOT NULL)",
      ]) {
        await query(sql);
      }
      await query(
        "INSERT INTO settings (id,halted) VALUES (1,$1) ON CONFLICT (id) DO NOTHING",
        [false],
      );
      await query("INSERT INTO schema_migrations (version) VALUES (1)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=2"))
        .length
    ) {
      await query(
        "CREATE TABLE users (id VARCHAR(36) PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, password_hash TEXT NOT NULL)",
      );
      await query(
        "CREATE TABLE user_settings (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), halted BOOLEAN NOT NULL)",
      );
      const owners = await query<{ username: string; password_hash: string }>(
        "SELECT username,password_hash FROM owners WHERE id=1",
      );
      if (owners.length) {
        await query("INSERT INTO users VALUES ($1,$2,$3)", [
          "legacy-owner",
          owners[0].username,
          owners[0].password_hash,
        ]);
        await query(
          "INSERT INTO user_settings SELECT $1,halted FROM settings WHERE id=1",
          ["legacy-owner"],
        );
      }
      for (const table of ["sessions", "strategies", "jobs", "events"]) {
        await query(
          `ALTER TABLE ${table} ADD COLUMN user_id VARCHAR(36) REFERENCES users(id)`,
        );
        if (owners.length) {
          await query(`UPDATE ${table} SET user_id=$1`, ["legacy-owner"]);
        }
        await query(`CREATE INDEX ${table}_user_idx ON ${table}(user_id)`);
      }
      await query("DROP TABLE owners");
      await query(
        "CREATE TABLE broker_credentials (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), ciphertext TEXT NOT NULL, updated_at VARCHAR(40) NOT NULL)",
      );
      await query(
        "CREATE TABLE worker_health (id INTEGER PRIMARY KEY, instance_id VARCHAR(36) NOT NULL, heartbeat DOUBLE PRECISION NOT NULL)",
      );
      await query("CREATE INDEX jobs_status_idx ON jobs(status,created_at)");
      await query("INSERT INTO schema_migrations VALUES (2)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=3"))
        .length
    ) {
      await query(
        "CREATE TABLE user_security (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), encrypted_secret TEXT NOT NULL, enabled BOOLEAN NOT NULL, last_counter BIGINT NOT NULL, recovery_hashes TEXT NOT NULL, pending_expires DOUBLE PRECISION NOT NULL)",
      );
      await query(
        "CREATE TABLE broker_usage (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), usage_day VARCHAR(10) NOT NULL, request_count INTEGER NOT NULL)",
      );
      await query("INSERT INTO schema_migrations VALUES (3)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=4"))
        .length
    ) {
      await query(
        "CREATE TABLE live_accounts (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), broker_binding TEXT NOT NULL UNIQUE, halted BOOLEAN NOT NULL DEFAULT TRUE, halt_reason TEXT NOT NULL, generation INTEGER NOT NULL DEFAULT 0, snapshot TEXT NOT NULL DEFAULT '', limits TEXT NOT NULL, reconciled_at DOUBLE PRECISION NOT NULL DEFAULT 0)",
      );
      await query(
        "CREATE TABLE live_orders (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), intent_key VARCHAR(100) NOT NULL, intent TEXT NOT NULL, state VARCHAR(24) NOT NULL CHECK (state IN ('reserved','submitting','unknown','blocked','acknowledged','open','partially_filled','filled','cancelled','rejected')), broker_order TEXT NOT NULL DEFAULT '', reserved_paise BIGINT NOT NULL, created_at DOUBLE PRECISION NOT NULL, UNIQUE(account_id,intent_key))",
      );
      await query(
        "CREATE INDEX live_orders_account_idx ON live_orders(account_id,state)",
      );
      await query(
        "CREATE TABLE live_spreads (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), plan TEXT NOT NULL, state VARCHAR(30) NOT NULL, detail TEXT NOT NULL DEFAULT '')",
      );
      await query(
        "CREATE TABLE live_events (id SERIAL PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), kind VARCHAR(40) NOT NULL, detail TEXT NOT NULL, created_at DOUBLE PRECISION NOT NULL)",
      );
      await query("INSERT INTO schema_migrations VALUES (4)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=5"))
        .length
    ) {
      await query(
        "CREATE TABLE live_permissions (account_id VARCHAR(36) PRIMARY KEY REFERENCES live_accounts(id), session_hash VARCHAR(64) NOT NULL, armed_until DOUBLE PRECISION NOT NULL, trading_day VARCHAR(10) NOT NULL)",
      );
      await query(
        "CREATE TABLE live_previews (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), session_hash VARCHAR(64) NOT NULL, intent TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL)",
      );
      await query(
        "CREATE TABLE broker_rpc_windows (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), window_start DOUBLE PRECISION NOT NULL, request_count INTEGER NOT NULL)",
      );
      await query("INSERT INTO schema_migrations VALUES (5)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=6"))
        .length
    ) {
      await query(
        "CREATE TABLE research_strategies (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), definition TEXT NOT NULL, created_at TEXT NOT NULL)",
      );
      await query(
        "CREATE INDEX research_strategies_owner_idx ON research_strategies(user_id)",
      );
      await query(
        "CREATE TABLE research_runs (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), strategy_id VARCHAR(36) NOT NULL REFERENCES research_strategies(id) ON DELETE CASCADE, result TEXT NOT NULL, created_at TEXT NOT NULL)",
      );
      await query(
        "CREATE INDEX research_runs_owner_idx ON research_runs(user_id)",
      );
      await query("INSERT INTO schema_migrations VALUES (6)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=7"))
        .length
    ) {
      await query("INSERT INTO schema_migrations VALUES(7)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=8"))
        .length
    ) {
      await query(
        "CREATE TABLE eod_instruments (id VARCHAR(120) PRIMARY KEY, symbol VARCHAR(60) NOT NULL, name VARCHAR(160) NOT NULL, kind VARCHAR(10) NOT NULL CHECK(kind IN ('equity','index')), series VARCHAR(10) NOT NULL, exchange VARCHAR(10) NOT NULL CHECK(exchange='NSE'))",
      );
      await query("CREATE INDEX eod_symbol_idx ON eod_instruments(symbol)");
      await query(
        "CREATE TABLE eod_candles (instrument_id VARCHAR(120) NOT NULL REFERENCES eod_instruments(id), day DATE NOT NULL, open DOUBLE PRECISION NOT NULL CHECK(open>0 AND open<'Infinity'::float8), high DOUBLE PRECISION NOT NULL CHECK(high>0 AND high<'Infinity'::float8), low DOUBLE PRECISION NOT NULL CHECK(low>0 AND low<'Infinity'::float8), close DOUBLE PRECISION NOT NULL CHECK(close>0 AND close<'Infinity'::float8), volume DOUBLE PRECISION CHECK(volume>=0 AND volume<'Infinity'::float8), source VARCHAR(200) NOT NULL, imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(instrument_id,day), CHECK(high>=low AND high>=open AND high>=close AND low<=open AND low<=close))",
      );
      await query("INSERT INTO schema_migrations VALUES(8)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=9"))
        .length
    ) {
      await query(
        "CREATE TABLE user_brokers (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), provider VARCHAR(40) NOT NULL CHECK(provider IN ('kotak','zerodha')), account_binding VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL CHECK(status IN ('connected','disconnected')), connected_at DOUBLE PRECISION NOT NULL, updated_at DOUBLE PRECISION NOT NULL, UNIQUE(user_id,id), UNIQUE(user_id,provider), UNIQUE(provider,account_binding))",
      );
      await query(
        "CREATE INDEX user_brokers_owner_status_idx ON user_brokers(user_id,status)",
      );
      await query(
        "ALTER TABLE user_settings ADD COLUMN active_broker_id VARCHAR(36)",
      );
      await query(
        "ALTER TABLE user_settings ADD CONSTRAINT user_settings_active_broker_owner_fk FOREIGN KEY(user_id,active_broker_id) REFERENCES user_brokers(user_id,id)",
      );
      await query("INSERT INTO schema_migrations VALUES(9)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=10"))
        .length
    ) {
      await query("ALTER TABLE live_accounts ADD COLUMN broker_id VARCHAR(36)");
      await query("ALTER TABLE live_orders ADD COLUMN broker_id VARCHAR(36)");
      await query("ALTER TABLE live_previews ADD COLUMN broker_id VARCHAR(36)");
      await query("ALTER TABLE live_spreads ADD COLUMN broker_id VARCHAR(36)");
      await query(
        "UPDATE live_accounts a SET broker_id=b.id FROM user_brokers b WHERE a.user_id=b.user_id AND a.broker_binding=b.account_binding",
      );
      await query(
        "UPDATE live_orders o SET broker_id=a.broker_id FROM live_accounts a WHERE o.account_id=a.id AND a.broker_id IS NOT NULL",
      );
      await query(
        "UPDATE live_previews p SET broker_id=a.broker_id FROM live_accounts a WHERE p.account_id=a.id AND a.broker_id IS NOT NULL",
      );
      await query(
        "UPDATE live_spreads s SET broker_id=a.broker_id FROM live_accounts a WHERE s.account_id=a.id AND a.broker_id IS NOT NULL",
      );
      await query(
        "ALTER TABLE live_accounts ADD CONSTRAINT live_accounts_broker_fk FOREIGN KEY(broker_id) REFERENCES user_brokers(id)",
      );
      await query(
        "ALTER TABLE live_orders ADD CONSTRAINT live_orders_broker_fk FOREIGN KEY(broker_id) REFERENCES user_brokers(id)",
      );
      await query(
        "ALTER TABLE live_previews ADD CONSTRAINT live_previews_broker_fk FOREIGN KEY(broker_id) REFERENCES user_brokers(id)",
      );
      await query(
        "ALTER TABLE live_spreads ADD CONSTRAINT live_spreads_broker_fk FOREIGN KEY(broker_id) REFERENCES user_brokers(id)",
      );
      await query(
        "ALTER TABLE live_orders DROP CONSTRAINT live_orders_state_check",
      );
      await query(
        "ALTER TABLE live_orders ADD CONSTRAINT live_orders_state_check CHECK (state IN ('bound','reserved','submitting','unknown','blocked','acknowledged','open','partially_filled','filled','cancelled','rejected'))",
      );
      await query(
        "CREATE INDEX live_orders_broker_idx ON live_orders(broker_id,state)",
      );
      await query("INSERT INTO schema_migrations VALUES(10)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=11"))
        .length
    ) {
      await query(
        "CREATE TABLE calculation_jobs (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), kind VARCHAR(30) NOT NULL CHECK(kind IN ('daily-backtest')), status VARCHAR(20) NOT NULL CHECK(status IN ('queued','running','completed','failed','cancelled')), progress INTEGER NOT NULL DEFAULT 0 CHECK(progress>=0 AND progress<=100), input TEXT NOT NULL, result TEXT NOT NULL DEFAULT '', error TEXT NOT NULL DEFAULT '', cancel_requested BOOLEAN NOT NULL DEFAULT FALSE, engine_version VARCHAR(80) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())",
      );
      await query(
        "CREATE INDEX calculation_jobs_owner_idx ON calculation_jobs(user_id,created_at DESC)",
      );
      await query(
        "CREATE INDEX calculation_jobs_queue_idx ON calculation_jobs(status,created_at)",
      );
      await query("INSERT INTO schema_migrations VALUES(11)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=12"))
        .length
    ) {
      await query(
        "CREATE TABLE option_chain_snapshots (user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider VARCHAR(40) NOT NULL, underlying VARCHAR(40) NOT NULL, expiry_date DATE NOT NULL, page_offset INTEGER NOT NULL CHECK(page_offset>=0), observed_at DOUBLE PRECISION NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(user_id,provider,underlying,expiry_date,page_offset,observed_at))",
      );
      await query(
        "CREATE INDEX option_chain_snapshots_lookup_idx ON option_chain_snapshots(user_id,underlying,expiry_date,page_offset,observed_at DESC)",
      );
      await query("INSERT INTO schema_migrations VALUES(12)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=13"))
        .length
    ) {
      await query(
        "CREATE TABLE option_eod_instruments (id VARCHAR(180) PRIMARY KEY, underlying VARCHAR(40) NOT NULL, expiry_date DATE NOT NULL, option_right VARCHAR(4) NOT NULL CHECK(option_right IN ('call','put')), strike_price DOUBLE PRECISION NOT NULL CHECK(strike_price>0 AND strike_price<'Infinity'::float8), exchange VARCHAR(10) NOT NULL CHECK(exchange='NSE'))",
      );
      await query(
        "CREATE INDEX option_eod_contract_idx ON option_eod_instruments(underlying,expiry_date,strike_price,option_right)",
      );
      await query(
        "CREATE TABLE option_eod_candles (instrument_id VARCHAR(180) NOT NULL REFERENCES option_eod_instruments(id) ON DELETE CASCADE, day DATE NOT NULL, open DOUBLE PRECISION NOT NULL CHECK(open>=0 AND open<'Infinity'::float8), high DOUBLE PRECISION NOT NULL CHECK(high>=0 AND high<'Infinity'::float8), low DOUBLE PRECISION NOT NULL CHECK(low>=0 AND low<'Infinity'::float8), close DOUBLE PRECISION NOT NULL CHECK(close>=0 AND close<'Infinity'::float8), settlement DOUBLE PRECISION CHECK(settlement>=0 AND settlement<'Infinity'::float8), volume BIGINT CHECK(volume>=0), open_interest BIGINT CHECK(open_interest>=0), change_open_interest BIGINT, lot_size INTEGER CHECK(lot_size>0), source VARCHAR(240) NOT NULL, imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(instrument_id,day), CHECK(close>0 OR settlement>0))",
      );
      await query(
        "CREATE INDEX option_eod_day_idx ON option_eod_candles(day,instrument_id)",
      );
      await query("INSERT INTO schema_migrations VALUES(13)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=14"))
        .length
    ) {
      await query(
        "ALTER TABLE option_eod_candles ADD COLUMN underlying_price DOUBLE PRECISION CHECK(underlying_price>0 AND underlying_price<'Infinity'::float8)",
      );
      await query("INSERT INTO schema_migrations VALUES(14)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=15"))
        .length
    ) {
      // Claim tokens fence late responses; expired leases, not API startup, permit recovery.
      await query(
        "ALTER TABLE calculation_jobs ADD COLUMN claim_token VARCHAR(36), ADD COLUMN lease_until TIMESTAMPTZ, ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0",
      );
      await query("INSERT INTO schema_migrations VALUES(15)");
    }
  });
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(684201)");
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=16"))
        .length
    ) {
      await query(
        "CREATE TABLE broker_sessions (user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE, session_hash VARCHAR(64) NOT NULL REFERENCES sessions(token_hash) ON DELETE CASCADE, provider VARCHAR(20) NOT NULL CHECK(provider IN ('kotak','zerodha')), expires DOUBLE PRECISION NOT NULL, ciphertext TEXT NOT NULL, PRIMARY KEY(session_hash,provider))",
      );
      await query("INSERT INTO schema_migrations VALUES(16)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=17"))
        .length
    ) {
      await query("DROP TABLE IF EXISTS paper_accounts");
      await query("INSERT INTO schema_migrations VALUES(17)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=18"))
        .length
    ) {
      await query(
        "CREATE TABLE broker_app_credentials (user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider VARCHAR(40) NOT NULL, ciphertext TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(user_id,provider))",
      );
      await query("INSERT INTO schema_migrations VALUES(18)");
    }
  });
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(684201)");
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=19"))
        .length
    ) {
      await query(
        "CREATE TABLE watchlists (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE, name VARCHAR(40) NOT NULL, is_default BOOLEAN NOT NULL DEFAULT false, items JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())",
      );
      await query(
        "CREATE UNIQUE INDEX watchlists_default_owner_idx ON watchlists(user_id) WHERE is_default",
      );
      await query("CREATE INDEX watchlists_owner_idx ON watchlists(user_id)");
      await query("INSERT INTO schema_migrations VALUES(19)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=20"))
        .length
    ) {
      await query(
        "ALTER TABLE user_settings ADD COLUMN mfa_failures INTEGER NOT NULL DEFAULT 0, ADD COLUMN mfa_locked_until DOUBLE PRECISION NOT NULL DEFAULT 0",
      );
      await query("INSERT INTO schema_migrations VALUES(20)");
    }
  });
  // The migration container owns DDL; API/worker use a separate non-superuser role.
  if (options.runtimePassword) {
    const password = options.runtimePassword;
    if (!/^[a-f0-9]{64}$/i.test(password)) {
      throw new Error(
        "APP_DATABASE_PASSWORD must be 64 random hex characters.",
      );
    }
    await store.transaction(async (query) => {
      await query("SELECT pg_advisory_xact_lock(684201)");
      if (
        !(await query("SELECT rolname FROM pg_roles WHERE rolname='nexus_app'"))
          .length
      ) {
        await query(
          "CREATE ROLE nexus_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE",
        );
      }
      // Restricted hex input above is necessary because role passwords cannot be SQL parameters.
      await query(`ALTER ROLE nexus_app PASSWORD '${password}'`);
      await query("GRANT USAGE ON SCHEMA public TO nexus_app");
      await query(
        "GRANT SELECT,INSERT,UPDATE,DELETE ON watchlists TO nexus_app",
      );
      await query(
        "GRANT SELECT,INSERT,UPDATE,DELETE ON broker_sessions,broker_app_credentials TO nexus_app",
      );
      await query(
        "GRANT SELECT ON eod_instruments,eod_candles,option_eod_instruments,option_eod_candles TO nexus_app",
      );
      await query(
        "GRANT SELECT,INSERT,UPDATE,DELETE ON users,user_settings,user_security,broker_usage,sessions,strategies,jobs,events,broker_credentials,worker_health,settings,live_accounts,live_orders,live_spreads,live_events,live_permissions,live_previews,broker_rpc_windows,research_strategies,research_runs,user_brokers,calculation_jobs,option_chain_snapshots TO nexus_app",
      );
      // Apply on upgrades too: a previous broad grant must not leave audit rows mutable.
      await query(
        "REVOKE UPDATE,DELETE,TRUNCATE ON live_events FROM nexus_app",
      );
      await query("GRANT SELECT,INSERT ON live_events TO nexus_app");
      await query(
        "GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO nexus_app",
      );
    });
  }
  if (options.backupPassword) {
    await provisionBackupRole(store, options.backupPassword);
  }
}

/** Only the migration administrator provisions this dedicated dump reader. */
export async function provisionBackupRole(store: Store, password: string) {
  if (!/^[a-f0-9]{64}$/i.test(password)) {
    throw new Error(
      "BACKUP_DATABASE_PASSWORD must be 64 random hex characters.",
    );
  }
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(684201)");
    if (
      !(
        await query("SELECT rolname FROM pg_roles WHERE rolname='nexus_backup'")
      ).length
    ) {
      await query(
        "CREATE ROLE nexus_backup LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS",
      );
    }
    await query(
      `ALTER ROLE nexus_backup WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '${password}'`,
    );
    await query("GRANT USAGE ON SCHEMA public TO nexus_backup");
    await query("GRANT SELECT ON ALL TABLES IN SCHEMA public TO nexus_backup");
    await query(
      "GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO nexus_backup",
    );
    await query(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO nexus_backup",
    );
    await query(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO nexus_backup",
    );
  });
}
/** Record a safe, user-visible event and retain the newest 2,000 events per account. No secrets. */
export const audit = async (query: Query, message: string, userId: string) => {
  await query(
    "INSERT INTO events (message,created_at,user_id) VALUES ($1,$2,$3)",
    [message, now(), userId],
  );
  await query(
    "DELETE FROM events WHERE user_id=$1 AND id NOT IN (SELECT id FROM events WHERE user_id=$1 ORDER BY id DESC LIMIT 2000)",
    [userId],
  );
};
/** Lock one tenant's controls, or the singleton coordination row for bootstrap/worker leases. */
export const lockWorkspaceSettings = async (
  query: Query,
  store: Store,
  userId?: string,
) =>
  userId
    ? (
        await query<Settings>(
          "SELECT * FROM user_settings WHERE user_id=$1 FOR UPDATE",
          [userId],
        )
      )[0]
    : (
        await query<Settings>("SELECT * FROM settings WHERE id=1 FOR UPDATE")
      )[0];

if (isEntryPoint(import.meta.url)) {
  const local =
    process.env.APP_ENV === "production" ||
    process.env.NODE_ENV === "production"
      ? null
      : readLocalPostgresConfiguration();
  const store = openDatabaseStore(
    process.env.MIGRATION_DATABASE_URL ||
      process.env.DATABASE_URL ||
      local?.adminUrl,
  );
  try {
    await runDatabaseMigrations(store, {
      runtimePassword:
        process.env.APP_DATABASE_PASSWORD || local?.applicationPassword,
      backupPassword: process.env.BACKUP_DATABASE_PASSWORD,
    });
    console.debug("Database migration complete.");
  } finally {
    await store.close();
  }
}
