/** Database adapter and forward-only schema migrations shared by API and paper worker.
 * PostgreSQL is the sole runtime database locally, in tests and on AWS.
 * Migrations transfer the legacy owner and data without resetting passwords or strategies.
 */
import { resolve } from "node:path";
import { readLocalPostgresConfiguration } from "./local-database.js";
import { fileURLToPath, pathToFileURL } from "node:url";
import pg from "pg";
import type { Settings } from "./types.js";

type Parameter = string | number | boolean | null;
export type Query = <T = Record<string, unknown>>(
  sql: string,
  params?: Parameter[],
) => Promise<T[]>;
export interface Store {
  transaction<T>(fn: (query: Query) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

export const root = fileURLToPath(
  new URL(import.meta.url.endsWith(".ts") ? "../" : "../../", import.meta.url),
);
export const now = () => new Date().toISOString();
export const isEntryPoint = (url: string) =>
  Boolean(
    process.argv[1] && url === pathToFileURL(resolve(process.argv[1])).href,
  );

/** Open one PostgreSQL pool. Local configuration is generated by make run; production
 * requires an explicit DATABASE_URL. No alternate database engine or SQL dialect exists here.
 */
export function openDatabaseStore(
  url = process.env.DATABASE_URL ||
    (process.env.APP_ENV !== "production" &&
    process.env.NODE_ENV !== "production"
      ? readLocalPostgresConfiguration()?.applicationUrl
      : undefined),
): Store {
  if (!url || !/^postgres(?:ql)?:\/\//.test(url))
    throw new Error(
      "A PostgreSQL DATABASE_URL is required. Run make run to initialize local PostgreSQL.",
    );
  const pool = new pg.Pool({
    connectionString: url,
    max: 5,
    connectionTimeoutMillis: 5000,
    idleTimeoutMillis: 30000,
    statement_timeout: 10000,
    query_timeout: 12000,
    idle_in_transaction_session_timeout: 15000,
  });
  pool.on("error", () =>
    console.error("Database idle connection failed; pool will replace it."),
  );
  const store: Store = {
    /** Commit the callback atomically; rollback failures discard the PostgreSQL connection.
     * Independent requests get independent connections, bounded by the configured pool size.
     */
    async transaction(fn) {
      let client: pg.PoolClient | null = null;
      let broken = false;
      try {
        client = await pool.connect();
        const query: Query = async <T>(
          sql: string,
          params: Parameter[] = [],
        ): Promise<T[]> => {
          return (await client!.query(sql, params)).rows as T[];
        };
        await query("BEGIN");
        try {
          const value = await fn(query);
          await query("COMMIT");
          return value;
        } catch (error) {
          try {
            await query("ROLLBACK");
          } catch {
            broken = true;
          }
          throw error;
        }
      } catch (error) {
        broken = true;
        throw error;
      } finally {
        client?.release(broken);
      }
    },
    /** Drain outstanding PostgreSQL clients during tests or graceful shutdown. */
    async close() {
      await pool.end();
    },
  };
  return store;
}

/** Apply each numbered schema change once, under a migration lock on PostgreSQL.
 * The runtime role gets DML privileges only; migration credentials are never given to the API.
 */
export async function runDatabaseMigrations(
  store: Store,
  options: { runtimePassword?: string; backupPassword?: string } = {
    runtimePassword: process.env.APP_DATABASE_PASSWORD,
    backupPassword: process.env.BACKUP_DATABASE_PASSWORD,
  },
) {
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(684201)");
    await query(
      "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY)",
    );
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=1"))
        .length
    ) {
      for (const sql of [
        "CREATE TABLE IF NOT EXISTS owners (id INTEGER PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, password_hash TEXT NOT NULL, failed_logins INTEGER NOT NULL, locked_until DOUBLE PRECISION NOT NULL)",
        "CREATE TABLE IF NOT EXISTS sessions (token_hash VARCHAR(64) PRIMARY KEY, csrf VARCHAR(100) NOT NULL, expires DOUBLE PRECISION NOT NULL)",
        "CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY, halted BOOLEAN NOT NULL)",
        "CREATE TABLE IF NOT EXISTS strategies (id VARCHAR(36) PRIMARY KEY, name VARCHAR(60) NOT NULL, symbol VARCHAR(20) NOT NULL, fast INTEGER NOT NULL, slow INTEGER NOT NULL, capital INTEGER NOT NULL, status VARCHAR(20) NOT NULL, pnl DOUBLE PRECISION NOT NULL, created_at VARCHAR(40) NOT NULL)",
        "CREATE TABLE IF NOT EXISTS jobs (id VARCHAR(36) PRIMARY KEY, strategy_id VARCHAR(36) NOT NULL, status VARCHAR(20) NOT NULL, result TEXT NOT NULL, created_at VARCHAR(40) NOT NULL, updated_at VARCHAR(40) NOT NULL)",
        "CREATE TABLE IF NOT EXISTS events (id SERIAL PRIMARY KEY, message TEXT NOT NULL, created_at VARCHAR(40) NOT NULL)",
      ])
        await query(sql);
      await query(
        "INSERT INTO settings (id,halted) VALUES (1,$1) ON CONFLICT (id) DO NOTHING",
        [false],
      );
      await query("INSERT INTO schema_migrations (version) VALUES (1)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=2"))
        .length
    ) {
      await query(
        "CREATE TABLE users (id VARCHAR(36) PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, password_hash TEXT NOT NULL)",
      );
      await query(
        "CREATE TABLE user_settings (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), halted BOOLEAN NOT NULL)",
      );
      const owners = await query<{ username: string; password_hash: string }>(
        "SELECT username,password_hash FROM owners WHERE id=1",
      );
      if (owners.length) {
        await query("INSERT INTO users VALUES ($1,$2,$3)", [
          "legacy-owner",
          owners[0].username,
          owners[0].password_hash,
        ]);
        await query(
          "INSERT INTO user_settings SELECT $1,halted FROM settings WHERE id=1",
          ["legacy-owner"],
        );
      }
      for (const table of ["sessions", "strategies", "jobs", "events"]) {
        await query(
          `ALTER TABLE ${table} ADD COLUMN user_id VARCHAR(36) REFERENCES users(id)`,
        );
        if (owners.length)
          await query(`UPDATE ${table} SET user_id=$1`, ["legacy-owner"]);
        await query(`CREATE INDEX ${table}_user_idx ON ${table}(user_id)`);
      }
      await query("DROP TABLE owners");
      await query(
        "CREATE TABLE broker_credentials (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), ciphertext TEXT NOT NULL, updated_at VARCHAR(40) NOT NULL)",
      );
      await query(
        "CREATE TABLE worker_health (id INTEGER PRIMARY KEY, instance_id VARCHAR(36) NOT NULL, heartbeat DOUBLE PRECISION NOT NULL)",
      );
      await query("CREATE INDEX jobs_status_idx ON jobs(status,created_at)");
      await query("INSERT INTO schema_migrations VALUES (2)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=3"))
        .length
    ) {
      await query(
        "CREATE TABLE user_security (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), encrypted_secret TEXT NOT NULL, enabled BOOLEAN NOT NULL, last_counter BIGINT NOT NULL, recovery_hashes TEXT NOT NULL, pending_expires DOUBLE PRECISION NOT NULL)",
      );
      await query(
        "CREATE TABLE broker_usage (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), usage_day VARCHAR(10) NOT NULL, request_count INTEGER NOT NULL)",
      );
      await query("INSERT INTO schema_migrations VALUES (3)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=4"))
        .length
    ) {
      await query(
        "CREATE TABLE live_accounts (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), broker_binding TEXT NOT NULL UNIQUE, halted BOOLEAN NOT NULL DEFAULT TRUE, halt_reason TEXT NOT NULL, generation INTEGER NOT NULL DEFAULT 0, snapshot TEXT NOT NULL DEFAULT '', limits TEXT NOT NULL, reconciled_at DOUBLE PRECISION NOT NULL DEFAULT 0)",
      );
      await query(
        "CREATE TABLE live_orders (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), intent_key VARCHAR(100) NOT NULL, intent TEXT NOT NULL, state VARCHAR(24) NOT NULL CHECK (state IN ('reserved','submitting','unknown','blocked','acknowledged','open','partially_filled','filled','cancelled','rejected')), broker_order TEXT NOT NULL DEFAULT '', reserved_paise BIGINT NOT NULL, created_at DOUBLE PRECISION NOT NULL, UNIQUE(account_id,intent_key))",
      );
      await query(
        "CREATE INDEX live_orders_account_idx ON live_orders(account_id,state)",
      );
      await query(
        "CREATE TABLE live_spreads (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), plan TEXT NOT NULL, state VARCHAR(30) NOT NULL, detail TEXT NOT NULL DEFAULT '')",
      );
      await query(
        "CREATE TABLE live_events (id SERIAL PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), kind VARCHAR(40) NOT NULL, detail TEXT NOT NULL, created_at DOUBLE PRECISION NOT NULL)",
      );
      await query("INSERT INTO schema_migrations VALUES (4)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=5"))
        .length
    ) {
      await query(
        "CREATE TABLE live_permissions (account_id VARCHAR(36) PRIMARY KEY REFERENCES live_accounts(id), session_hash VARCHAR(64) NOT NULL, armed_until DOUBLE PRECISION NOT NULL, trading_day VARCHAR(10) NOT NULL)",
      );
      await query(
        "CREATE TABLE live_previews (id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36) NOT NULL REFERENCES live_accounts(id), session_hash VARCHAR(64) NOT NULL, intent TEXT NOT NULL, expires DOUBLE PRECISION NOT NULL)",
      );
      await query(
        "CREATE TABLE broker_rpc_windows (user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id), window_start DOUBLE PRECISION NOT NULL, request_count INTEGER NOT NULL)",
      );
      await query("INSERT INTO schema_migrations VALUES (5)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=6"))
        .length
    ) {
      await query(
        "CREATE TABLE research_strategies (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), definition TEXT NOT NULL, created_at TEXT NOT NULL)",
      );
      await query(
        "CREATE INDEX research_strategies_owner_idx ON research_strategies(user_id)",
      );
      await query(
        "CREATE TABLE research_runs (id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL REFERENCES users(id), strategy_id VARCHAR(36) NOT NULL REFERENCES research_strategies(id) ON DELETE CASCADE, result TEXT NOT NULL, created_at TEXT NOT NULL)",
      );
      await query(
        "CREATE INDEX research_runs_owner_idx ON research_runs(user_id)",
      );
      await query("INSERT INTO schema_migrations VALUES (6)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=7"))
        .length
    ) {
      await query(
        "CREATE TABLE paper_accounts (user_id VARCHAR(36) NOT NULL REFERENCES users(id), broker VARCHAR(10) NOT NULL CHECK (broker = 'kotak'), ledger TEXT NOT NULL, PRIMARY KEY(user_id,broker))",
      );
      await query("INSERT INTO schema_migrations VALUES(7)");
    }
  });
  // The migration container owns DDL; API/worker use a separate non-superuser role.
  if (options.runtimePassword) {
    const password = options.runtimePassword;
    if (!/^[a-f0-9]{64}$/i.test(password))
      throw new Error(
        "APP_DATABASE_PASSWORD must be 64 random hex characters.",
      );
    await store.transaction(async (query) => {
      await query("SELECT pg_advisory_xact_lock(684201)");
      if (
        !(await query("SELECT rolname FROM pg_roles WHERE rolname='nexus_app'"))
          .length
      )
        await query(
          "CREATE ROLE nexus_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE",
        );
      // Restricted hex input above is necessary because role passwords cannot be SQL parameters.
      await query(`ALTER ROLE nexus_app PASSWORD '${password}'`);
      await query("GRANT USAGE ON SCHEMA public TO nexus_app");
      await query(
        "GRANT SELECT,INSERT,UPDATE,DELETE ON users,user_settings,user_security,broker_usage,sessions,strategies,jobs,events,broker_credentials,worker_health,settings,live_accounts,live_orders,live_spreads,live_events,live_permissions,live_previews,broker_rpc_windows,research_strategies,research_runs,paper_accounts TO nexus_app",
      );
      await query(
        "GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO nexus_app",
      );
    });
  }
  if (options.backupPassword)
    await provisionBackupRole(store, options.backupPassword);
}

/** Only the migration administrator provisions this dedicated dump reader. */
export async function provisionBackupRole(store: Store, password: string) {
  if (!/^[a-f0-9]{64}$/i.test(password))
    throw new Error(
      "BACKUP_DATABASE_PASSWORD must be 64 random hex characters.",
    );
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(684201)");
    if (
      !(
        await query("SELECT rolname FROM pg_roles WHERE rolname='nexus_backup'")
      ).length
    )
      await query(
        "CREATE ROLE nexus_backup LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS",
      );
    await query(
      `ALTER ROLE nexus_backup WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '${password}'`,
    );
    await query("GRANT USAGE ON SCHEMA public TO nexus_backup");
    await query("GRANT SELECT ON ALL TABLES IN SCHEMA public TO nexus_backup");
    await query(
      "GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO nexus_backup",
    );
    await query(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO nexus_backup",
    );
    await query(
      "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO nexus_backup",
    );
  });
}
/** Record a safe, user-visible event and retain the newest 2,000 events per account. No secrets. */
export const audit = async (query: Query, message: string, userId: string) => {
  await query(
    "INSERT INTO events (message,created_at,user_id) VALUES ($1,$2,$3)",
    [message, now(), userId],
  );
  await query(
    "DELETE FROM events WHERE user_id=$1 AND id NOT IN (SELECT id FROM events WHERE user_id=$1 ORDER BY id DESC LIMIT 2000)",
    [userId],
  );
};
/** Lock one tenant's controls, or the singleton coordination row for bootstrap/worker leases. */
export const lockWorkspaceSettings = async (
  query: Query,
  store: Store,
  userId?: string,
) =>
  userId
    ? (
        await query<Settings>(
          "SELECT * FROM user_settings WHERE user_id=$1 FOR UPDATE",
          [userId],
        )
      )[0]
    : (
        await query<Settings>("SELECT * FROM settings WHERE id=1 FOR UPDATE")
      )[0];

if (isEntryPoint(import.meta.url)) {
  const local =
    process.env.APP_ENV === "production" ||
    process.env.NODE_ENV === "production"
      ? null
      : readLocalPostgresConfiguration();
  const store = openDatabaseStore(
    process.env.MIGRATION_DATABASE_URL ||
      process.env.DATABASE_URL ||
      local?.adminUrl,
  );
  try {
    await runDatabaseMigrations(store, {
      runtimePassword:
        process.env.APP_DATABASE_PASSWORD || local?.applicationPassword,
      backupPassword: process.env.BACKUP_DATABASE_PASSWORD,
    });
    console.log("Database migration complete.");
  } finally {
    await store.close();
  }
}
