/** Pure-model and real-PostgreSQL API tests. All ICICI market responses are generated by
 * network-free doubles; there is no broker account access or real-money execution here.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  researchStrategySchema,
  normalizeHistoricalCandles,
  simulateHistoricalBasket,
  normalizeResearchQuote,
  sessionTimestamp,
} from "../dist/backend/strategy-lab.js";
import { createBreezeData } from "../dist/backend/breeze.js";
import { BrokerManager } from "../dist/backend/brokers.js";
import { createApiApplication } from "../dist/backend/main.js";
import { runDatabaseMigrations } from "../dist/backend/database.js";
import { createPostgresTestStore } from "./postgres-fixture.mjs";

const day = "2025-01-02";
const cash = {
  name: "Cash research",
  market: "cash",
  legs: [{ stockCode: "TEST", side: "buy", quantity: 2 }],
  capital: 10000,
  marginReserve: 0,
  entryTime: "09:20",
  exitTime: "09:30",
  stopLoss: 1000,
  targetProfit: 1000,
  slippageBps: 0,
  feePerOrder: 1,
};
const options = {
  ...cash,
  name: "Option spread",
  market: "options",
  marginReserve: 1000,
  legs: [
    {
      stockCode: "NIFTY",
      side: "buy",
      quantity: 10,
      expiryDate: "2025-01-30",
      right: "call",
      strikePrice: 24000,
    },
    {
      stockCode: "NIFTY",
      side: "sell",
      quantity: 10,
      expiryDate: "2025-01-30",
      right: "call",
      strikePrice: 24500,
    },
  ],
};
/** Build tiny transparent fixtures so cashflows, timing and look-ahead can be checked by hand. */
function rawBars(prices = [100, 100, 110, 120]) {
  return prices.map((price, i) => ({
    datetime: `${day} 09:${15 + i * 5}:00`,
    open: price,
    high: price + 2,
    low: price - 2,
    close: price,
  }));
}
const bars = (prices) => normalizeHistoricalCandles(rawBars(prices), day, 5);

test("historical cash replay uses scheduled opens, charges both fills and never calls a broker", () => {
  const result = simulateHistoricalBasket(cash, [bars()], day);
  assert.equal(result.pnl, 38);
  assert.equal(result.totalFees, 2);
  assert.equal(result.fills.length, 2);
  assert.equal(result.fills[0].time, sessionTimestamp(day, "09:20"));
  assert.equal(result.fills[1].time, sessionTimestamp(day, "09:30"));
  assert.equal(result.points.at(-1).open, false);
  assert.equal(result.source, "icici-breeze");
});
test("a stop observed at candle close fills only at the next open, including price gaps", () => {
  const history = bars([100, 100, 50, 40]);
  history[1] = { ...history[1], close: 80, low: 80 };
  const result = simulateHistoricalBasket(
    { ...cash, stopLoss: 10 },
    [history],
    day,
  );
  assert.equal(result.fills[1].time, sessionTimestamp(day, "09:25"));
  assert.equal(result.fills[1].price, 50);
  assert.equal(result.pnl, -102);
  const changed = structuredClone(history);
  changed[3].close = 900;
  assert.deepEqual(
    simulateHistoricalBasket(
      { ...cash, stopLoss: 10 },
      [changed],
      day,
    ).points.slice(0, 3),
    result.points.slice(0, 3),
  );
});
test("multi-leg options P&L applies direction, units and per-leg entry/exit fees", () => {
  const result = simulateHistoricalBasket(
    options,
    [bars(), bars([80, 80, 85, 90])],
    day,
  );
  assert.equal(result.pnl, 96);
  assert.equal(result.fills.length, 4);
  assert.equal(result.fills[1].action, "sell");
  assert.equal(result.fills[3].action, "buy");
  assert.ok(result.warnings.some((message) => message.includes("SPAN")));
});
test("invalid cash shorts, incomplete option contracts and duplicate legs cannot be saved", () => {
  assert.equal(
    researchStrategySchema.safeParse({
      ...cash,
      legs: [{ ...cash.legs[0], side: "sell" }],
    }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({ ...cash, market: "options" }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({ ...options, marginReserve: 0 }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({
      ...options,
      legs: [options.legs[0], options.legs[0]],
    }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({ ...cash, live: true }).success,
    false,
  );
});
test("gaps, duplicates, invalid OHLC and out-of-session timestamps fail rather than fabricate history", () => {
  assert.throws(() => normalizeHistoricalCandles([], day, 5));
  assert.throws(
    () =>
      normalizeHistoricalCandles(
        rawBars().filter((_, i) => i !== 1),
        day,
        5,
      ),
    /gaps/,
  );
  assert.throws(
    () => normalizeHistoricalCandles([...rawBars(), rawBars()[0]], day, 5),
    /duplicate/,
  );
  assert.throws(
    () =>
      normalizeHistoricalCandles(
        [{ ...rawBars()[0], high: 1 }, ...rawBars().slice(1)],
        day,
        5,
      ),
    /OHLC/,
  );
  assert.throws(
    () => normalizeHistoricalCandles(rawBars(), "2025-01-03", 5),
    /session/,
  );
});
test("unaligned legs, expired contracts, missing exit bars and unfunded baskets are rejected", () => {
  assert.throws(
    () => simulateHistoricalBasket(options, [bars(), bars().slice(1)], day),
    /timeline/,
  );
  assert.throws(
    () =>
      simulateHistoricalBasket(
        {
          ...options,
          legs: options.legs.map((leg) => ({
            ...leg,
            expiryDate: "2025-01-01",
          })),
        },
        [bars(), bars()],
        day,
      ),
    /expired/,
  );
  assert.throws(
    () => simulateHistoricalBasket(cash, [bars().slice(0, 2)], day),
    /cover/,
  );
  assert.throws(
    () => simulateHistoricalBasket({ ...cash, capital: 100 }, [bars()], day),
    /capital/,
  );
});
test("quote freshness uses exchange timestamps, and wrong options contract identity is rejected", () => {
  const quote = {
    stock_code: "NIFTY",
    exchange_code: "NFO",
    expiry_date: "30-Jan-2025",
    right: "Call",
    strike_price: 24000,
    ltp: 100,
    best_bid_price: 99,
    best_offer_price: 101,
    ltt: "02-Jan-2025 09:20:00",
  };
  assert.equal(
    normalizeResearchQuote([quote], options, options.legs[0]).stale,
    true,
  );
  assert.throws(
    () =>
      normalizeResearchQuote(
        [{ ...quote, strike_price: 25000 }],
        options,
        options.legs[0],
      ),
    /contract/,
  );
  assert.throws(
    () =>
      normalizeResearchQuote(
        [{ ...quote, stock_code: "OTHER" }],
        options,
        options.legs[0],
      ),
    /instrument/,
  );
});
test("data-only SDK quotes reject broker errors without exposing secret-bearing exceptions", async () => {
  class FakeSdk {
    async generateSession() {}
    async getQuotes() {
      return { Status: 500, Error: "fake-secret" };
    }
  }
  const adapter = createBreezeData(
    { apiKey: "fake", apiSecret: "fake", sessionToken: "fake" },
    FakeSdk,
  );
  await adapter.connect();
  await assert.rejects(
    adapter.quotes({ stockCode: "TEST", exchangeCode: "NSE" }),
    { message: "Breeze quote request failed." },
  );
  assert.equal("placeOrder" in adapter, false);
  adapter.disconnect();
});
test("research source graph cannot import live execution or submit orders", () => {
  for (const path of [
    "backend/strategy-lab.ts",
    "backend/research-routes.ts",
    "backend/research-stream.ts",
    "frontend/src/components/option-chain-picker.tsx",
    "frontend/src/components/strategy-lab-panel.tsx",
  ]) {
    const text = readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
    assert.doesNotMatch(
      text,
      /placeOrder\(|\/live\/icici\/orders|from ["']\.\/live\//,
    );
  }
});

/** Allocate two independent cookie jars against an isolated PostgreSQL schema. */
async function fixture(t) {
  const store = await createPostgresTestStore();
  await runDatabaseMigrations(store, {});
  const calls = [];
  let missing = false;
  const brokers = new BrokerManager(() => ({
    async call(method, params) {
      calls.push({ method, params });
      if (method === "subscribeBasket") {
        this.stream = {
          streamId: params.streamId,
          strategyId: params.strategyId,
          state: "waiting",
          quotes: [],
        };
        return { ok: true };
      }
      if (method === "stopBasket") {
        if (this.stream?.streamId === params.streamId) this.stream = null;
        return { ok: true };
      }
      if (method === "optionChain")
        return [
          {
            stock_code: params.stockCode,
            exchange_code: "NFO",
            expiry_date: params.expiryDate,
            right: params.right,
            strike_price: 24000,
            ltp: 100,
            best_bid_price: 99,
            best_offer_price: 101,
            ltt: "02-Jan-2025 09:20:00",
            open_interest: 100,
            total_quantity_traded: 200,
          },
        ];
      if (method === "historical") return missing ? [] : rawBars();
      if (method === "quotes")
        return [
          {
            stock_code: params.stockCode,
            exchange_code: params.exchangeCode,
            ltp: 100,
            best_bid_price: 99,
            best_offer_price: 101,
            ltt: "02-Jan-2025 09:20:00",
            expiry_date: params.expiryDate,
            right: params.right,
            strike_price: params.strikePrice,
          },
        ];
      return { ok: true };
    },
    close() {
      this.stream = null;
    },
    researchSnapshot(streamId) {
      return this.stream?.streamId === streamId ? this.stream : null;
    },
    snapshot() {
      return { state: "connected", tick: null, receivedAt: null };
    },
  }));
  const app = createApiApplication(
    store,
    { BROKER_ENCRYPTION_KEY: "ab".repeat(32) },
    brokers,
  );
  const server = app.listen(0, "127.0.0.1");
  await new Promise((resolve) => server.once("listening", resolve));
  t.after(async () => {
    await app.locals.shutdown();
    await new Promise((resolve) => server.close(resolve));
    await store.close();
  });
  function client() {
    let cookie = "",
      csrf = "";
    return async (path, method = "GET", body, headers = {}) => {
      const response = await fetch(
        `http://127.0.0.1:${server.address().port}/api${path}`,
        {
          method,
          headers: {
            cookie,
            "X-CSRF-Token": csrf,
            "Content-Type": "application/json",
            ...headers,
          },
          ...(body === undefined ? {} : { body: JSON.stringify(body) }),
        },
      );
      if (response.headers.get("set-cookie"))
        cookie = response.headers.get("set-cookie").split(";")[0];
      const data = await response.json();
      if (data.csrf) csrf = data.csrf;
      return { status: response.status, data };
    };
  }
  const first = client(),
    second = client();
  await first("/auth/setup", "POST", {
    username: "research-owner",
    password: "research-password-long",
  });
  await second("/auth/register", "POST", {
    username: "research-second",
    password: "research-second-password",
  });
  await first("/brokers/icici/connect", "POST", {
    apiKey: "fake-api-key",
    apiSecret: "fake-api-secret",
    sessionToken: "fake-session",
  });
  return {
    first,
    second,
    calls,
    store,
    setMissing: () => {
      missing = true;
    },
  };
}
test("research API persists immutable results, scopes every ID by owner, and enforces CSRF", async (t) => {
  const { first, second, calls } = await fixture(t);
  assert.equal(
    (
      await first("/research/strategies", "POST", cash, {
        "X-CSRF-Token": "wrong",
      })
    ).status,
    403,
  );
  const saved = await first("/research/strategies", "POST", cash);
  assert.equal(saved.status, 201);
  assert.equal((await second("/research")).data.strategies.length, 0);
  assert.equal(
    (
      await second("/research/backtest", "POST", {
        strategyId: saved.data.id,
        day,
        interval: "5minute",
      })
    ).status,
    404,
  );
  const result = await first("/research/backtest", "POST", {
    strategyId: saved.data.id,
    day,
    interval: "5minute",
  });
  assert.equal(result.status, 200, JSON.stringify(result.data));
  assert.equal(result.data.pnl, 38);
  assert.equal(
    calls.find((call) => call.method === "historical").params.fromDate,
    "2025-01-02 09:15:00",
  );
  assert.equal((await first(`/research/runs/${result.data.id}`)).data.pnl, 38);
  assert.equal((await second(`/research/runs/${result.data.id}`)).status, 404);
  assert.equal(
    (await second(`/research/strategies/${saved.data.id}`, "DELETE")).status,
    404,
  );
  assert.equal(
    (await first("/research/quotes", "POST", { strategyId: saved.data.id }))
      .data.quotes[0].stale,
    true,
  );
  assert.equal((await first("/live/icici")).data.armed, false);
  assert.ok(
    calls.every((call) =>
      ["connect", "historical", "quotes"].includes(call.method),
    ),
  );
  assert.equal(
    (await first(`/research/strategies/${saved.data.id}`, "DELETE")).status,
    200,
  );
  assert.equal((await first(`/research/runs/${result.data.id}`)).status, 404);
});

test("chain picker and stream endpoints enforce owner scope, CSRF, exact-generation stop and no options execution", async (t) => {
  const { first, second, calls } = await fixture(t);
  const chain = await first("/research/option-chain", "POST", {
    stockCode: "NIFTY",
    expiryDate: "2030-01-31",
  });
  assert.equal(chain.status, 200, JSON.stringify(chain.data));
  assert.equal(chain.data.contracts.length, 2);
  assert.equal(chain.data.complete, false);
  const saved = await first("/research/strategies", "POST", cash);
  assert.equal(
    (
      await first(
        "/research/stream",
        "POST",
        { strategyId: saved.data.id },
        { "X-CSRF-Token": "wrong" },
      )
    ).status,
    403,
  );
  const opened = await first("/research/stream", "POST", {
    strategyId: saved.data.id,
  });
  assert.equal(opened.status, 200, JSON.stringify(opened.data));
  const path = `/research/stream?strategyId=${saved.data.id}&streamId=${opened.data.streamId}`;
  assert.equal((await first(path)).status, 200);
  assert.equal((await second(path)).status, 404);
  await second("/research/stream/stop", "POST", {
    streamId: opened.data.streamId,
  });
  assert.equal((await first(path)).status, 200);
  const next = await first("/research/stream", "POST", {
    strategyId: saved.data.id,
  });
  await first("/research/stream/stop", "POST", {
    streamId: opened.data.streamId,
  });
  const nextPath = `/research/stream?strategyId=${saved.data.id}&streamId=${next.data.streamId}`;
  assert.equal((await first(nextPath)).status, 200);
  assert.equal((await first(path)).status, 409);
  await first("/research/stream/stop", "POST", {
    streamId: next.data.streamId,
  });
  assert.equal((await first(nextPath)).status, 409);
  const expired = await first("/research/strategies", "POST", options);
  assert.equal(
    (await first("/research/stream", "POST", { strategyId: expired.data.id }))
      .status,
    422,
  );
  assert.ok(!calls.some((call) => call.method === "placeOrder"));
});
test("options research fetches each exact contract and stays data-only", async (t) => {
  const { first, calls } = await fixture(t);
  const saved = await first("/research/strategies", "POST", options);
  const result = await first("/research/backtest", "POST", {
    strategyId: saved.data.id,
    day,
    interval: "5minute",
  });
  assert.equal(result.status, 200, JSON.stringify(result.data));
  assert.equal(result.data.fills.length, 4);
  const historyCalls = calls.filter((call) => call.method === "historical");
  assert.equal(historyCalls.length, 2);
  assert.equal(historyCalls[1].params.strikePrice, "24500");
  assert.equal(historyCalls[0].params.exchangeCode, "NFO");
  const quotes = await first("/research/quotes", "POST", {
    strategyId: saved.data.id,
  });
  assert.equal(quotes.status, 200, JSON.stringify(quotes.data));
  assert.equal(quotes.data.optionsExecutionEnabled, false);
});
test("missing history, future sessions and exhausted market-data budgets never produce fake results", async (t) => {
  const { first, store, setMissing } = await fixture(t);
  const saved = await first("/research/strategies", "POST", cash);
  assert.equal(
    (
      await first("/research/backtest", "POST", {
        strategyId: saved.data.id,
        day: "2099-01-01",
        interval: "5minute",
      })
    ).status,
    422,
  );
  setMissing();
  assert.equal(
    (
      await first("/research/backtest", "POST", {
        strategyId: saved.data.id,
        day,
        interval: "5minute",
      })
    ).status,
    422,
  );
  assert.equal((await first("/research")).data.runs.length, 0);
  await store.transaction((query) =>
    query("UPDATE broker_usage SET request_count=4000"),
  );
  assert.equal(
    (await first("/research/quotes", "POST", { strategyId: saved.data.id }))
      .status,
    429,
  );
});
