/** Pure-model tests. Market responses are generated by
 * network-free doubles; there is no broker account access or real-money execution here.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  researchStrategySchema,
  normalizeHistoricalCandles,
  simulateHistoricalBasket,
  summarizeBacktestBatch,
  sessionTimestamp,
} from "../../dist/backend/historical-strategy-simulator.js";

const day = "2025-01-02";
const cash = {
  broker: "kotak",
  name: "Cash research",
  market: "cash",
  legs: [{ stockCode: "TEST", side: "buy", quantity: 2 }],
  capital: 10000,
  marginReserve: 0,
  entryTime: "09:20",
  exitTime: "09:30",
  stopLoss: 1000,
  targetProfit: 1000,
  slippageBps: 0,
  feePerOrder: 1,
};
const options = {
  ...cash,
  name: "Option spread",
  market: "options",
  marginReserve: 1000,
  legs: [
    {
      stockCode: "NIFTY",
      side: "buy",
      quantity: 10,
      expiryDate: "2025-01-30",
      right: "call",
      strikePrice: 24000,
    },
    {
      stockCode: "NIFTY",
      side: "sell",
      quantity: 10,
      expiryDate: "2025-01-30",
      right: "call",
      strikePrice: 24500,
    },
  ],
};
/** Build tiny transparent fixtures so cashflows, timing and look-ahead can be checked by hand. */
function rawBars(prices = [100, 100, 110, 120]) {
  return prices.map((price, i) => ({
    datetime: `${day} 09:${15 + i * 5}:00`,
    open: price,
    high: price + 2,
    low: price - 2,
    close: price,
  }));
}
const bars = (prices) => normalizeHistoricalCandles(rawBars(prices), day, 5);

test("historical cash replay uses scheduled opens, charges both fills and never calls a broker", () => {
  const result = simulateHistoricalBasket(cash, [bars()], day);
  assert.equal(result.pnl, 38);
  assert.equal(result.totalFees, 2);
  assert.equal(result.fills.length, 2);
  assert.equal(result.fills[0].time, sessionTimestamp(day, "09:20"));
  assert.equal(result.fills[1].time, sessionTimestamp(day, "09:30"));
  assert.equal(result.points.at(-1).open, false);
  assert.equal(result.source, "kotak");
});
test("a stop observed at candle close fills only at the next open, including price gaps", () => {
  const history = bars([100, 100, 50, 40]);
  history[1] = { ...history[1], close: 80, low: 80 };
  const result = simulateHistoricalBasket(
    { ...cash, stopLoss: 10 },
    [history],
    day,
  );
  assert.equal(result.fills[1].time, sessionTimestamp(day, "09:25"));
  assert.equal(result.fills[1].price, 50);
  assert.equal(result.pnl, -102);
  const changed = structuredClone(history);
  changed[3].close = 900;
  assert.deepEqual(
    simulateHistoricalBasket(
      { ...cash, stopLoss: 10 },
      [changed],
      day,
    ).points.slice(0, 3),
    result.points.slice(0, 3),
  );
});
test("multi-leg options P&L applies direction, units and per-leg entry/exit fees", () => {
  const result = simulateHistoricalBasket(
    options,
    [bars(), bars([80, 80, 85, 90])],
    day,
  );
  assert.equal(result.pnl, 96);
  assert.equal(result.fills.length, 4);
  assert.equal(result.fills[1].action, "sell");
  assert.equal(result.fills[3].action, "buy");
  assert.ok(result.warnings.some((message) => message.includes("SPAN")));
});
test("invalid cash shorts, incomplete option contracts and duplicate legs cannot be saved", () => {
  assert.equal(
    researchStrategySchema.safeParse({
      ...cash,
      legs: [{ ...cash.legs[0], side: "sell" }],
    }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({ ...cash, market: "options" }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({ ...options, marginReserve: 0 }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({
      ...options,
      legs: [options.legs[0], options.legs[0]],
    }).success,
    false,
  );
  assert.equal(
    researchStrategySchema.safeParse({ ...cash, live: true }).success,
    false,
  );
});
test("gaps, duplicates, invalid OHLC and out-of-session timestamps fail rather than fabricate history", () => {
  assert.throws(() => normalizeHistoricalCandles([], day, 5));
  assert.throws(
    () =>
      normalizeHistoricalCandles(
        rawBars().filter((_, i) => i !== 1),
        day,
        5,
      ),
    /gaps/,
  );
  assert.throws(
    () => normalizeHistoricalCandles([...rawBars(), rawBars()[0]], day, 5),
    /duplicate/,
  );
  assert.throws(
    () =>
      normalizeHistoricalCandles(
        [{ ...rawBars()[0], high: 1 }, ...rawBars().slice(1)],
        day,
        5,
      ),
    /OHLC/,
  );
  assert.throws(
    () => normalizeHistoricalCandles(rawBars(), "2025-01-03", 5),
    /session/,
  );
});
test("unaligned legs, expired contracts, missing exit bars and unfunded baskets are rejected", () => {
  assert.throws(
    () => simulateHistoricalBasket(options, [bars(), bars().slice(1)], day),
    /timeline/,
  );
  assert.throws(
    () =>
      simulateHistoricalBasket(
        {
          ...options,
          legs: options.legs.map((leg) => ({
            ...leg,
            expiryDate: "2025-01-01",
          })),
        },
        [bars(), bars()],
        day,
      ),
    /expired/,
  );
  assert.throws(
    () => simulateHistoricalBasket(cash, [bars().slice(0, 2)], day),
    /cover/,
  );
  assert.throws(
    () => simulateHistoricalBasket({ ...cash, capital: 100 }, [bars()], day),
    /capital/,
  );
});
test("research source graph cannot import live execution or submit orders", () => {
  for (const path of [
    "backend/historical-strategy-simulator.ts",
    "backend/strategy-research-routes.ts",
    "frontend/src/components/option-chain-picker.tsx",
    "frontend/src/features/strategy-lab/strategy-lab-screen.tsx",
  ]) {
    const text = readFileSync(
      new URL(`../../${path}`, import.meta.url),
      "utf8",
    );
    assert.doesNotMatch(text, /placeOrder\(|from ["']\.\/live\//);
  }
});

test("batch summary separates break-even days and reports per-session drawdown/fills", () => {
  const base = simulateHistoricalBasket(
    cash,
    [normalizeHistoricalCandles(rawBars(), day, 5)],
    day,
  );
  const summary = summarizeBacktestBatch([
    { ...base, pnl: 10.11, drawdown: 2 },
    { ...base, day: "2025-01-03", pnl: -3.01, drawdown: 5 },
    { ...base, day: "2025-01-06", pnl: 0, drawdown: 1 },
  ]);
  assert.equal(summary.totalPnl, 7.1);
  assert.equal(summary.averagePnlPerSession, 2.37);
  assert.equal(summary.winningSessions, 1);
  assert.equal(summary.losingSessions, 1);
  assert.equal(summary.breakEvenSessions, 1);
  assert.equal(summary.worstSessionDrawdown, 5);
  assert.equal(summary.sessions[0].trades, base.fills.length);
  assert.throws(() => summarizeBacktestBatch([]), /No completed/);
});
